import { IconType } from "react-icons";
import {
    FaCode,
    FaSearch,
    FaHandHoldingUsd,
    FaEnvelopeOpenText,
    FaUsers,
    FaChartLine,
    FaPalette,
    FaRocket,
    FaLightbulb,
    FaCog,
    FaShieldAlt,
    FaMobile,
    FaDesktop,
    FaDatabase,
    FaCloud,
    FaLock,
    FaBolt,
    FaHeart,
    FaStar,
    FaCheckCircle,
    FaGlobe,
    FaCamera,
    FaMusic,
    FaVideo,
    FaGamepad,
    FaShoppingCart,
    FaCreditCard,
    FaTruck,
    FaMapMarkerAlt,
    FaPhone,
    FaEnvelope,
    FaComments,
    FaBell,
    FaCalendar,
    FaClock,
    FaFileAlt,
    FaFolder,
    FaDownload,
    FaUpload,
    FaPrint,
    FaShare,
    FaEdit,
    FaTrash,
    FaSave,
    FaPlus,
    FaMinus,
} from "react-icons/fa";
import {
    BsBarChartLineFill,
    BsCheckCircleFill,
    BsAwardFill,
    BsLightningFill,
    BsShieldFillCheck,
    BsGearFill,
    BsGraphUpArrow,
    BsPeopleFill,
    BsStarFill,
    BsHeartFill,
    BsCloudFill,
    BsRocketFill,
    BsBriefcaseFill,
    BsChatDotsFill,
    BsBellFill,
    BsCalendarFill,
    BsClockFill,
    BsFileEarmarkFill,
    BsFolderFill,
    BsCartFill,
    BsCreditCardFill,
    BsTrophyFill,
    BsGiftFill,
    BsBookFill,
    BsCameraFill,
    BsMusicNoteBeamed,
    BsPlayCircleFill,
} from "react-icons/bs";

// Icon mapping object
export const iconMap: Record<string, IconType> = {
    // Font Awesome Icons
    FaCode,
    FaSearch,
    FaHandHoldingUsd,
    FaEnvelopeOpenText,
    FaUsers,
    FaChartLine,
    FaPalette,
    FaRocket,
    FaLightbulb,
    FaCog,
    FaShieldAlt,
    FaMobile,
    FaDesktop,
    FaDatabase,
    FaCloud,
    FaLock,
    FaBolt,
    FaHeart,
    FaStar,
    FaCheckCircle,
    FaGlobe,
    FaCamera,
    FaMusic,
    FaVideo,
    FaGamepad,
    FaShoppingCart,
    FaCreditCard,
    FaTruck,
    FaMapMarkerAlt,
    FaPhone,
    FaEnvelope,
    FaComments,
    FaBell,
    FaCalendar,
    FaClock,
    FaFileAlt,
    FaFolder,
    FaDownload,
    FaUpload,
    FaPrint,
    FaShare,
    FaEdit,
    FaTrash,
    FaSave,
    FaPlus,
    FaMinus,

    // Bootstrap Icons
    BsBarChartLineFill,
    BsCheckCircleFill,
    BsAwardFill,
    BsLightningFill,
    BsShieldFillCheck,
    BsGearFill,
    BsGraphUpArrow,
    BsPeopleFill,
    BsStarFill,
    BsHeartFill,
    BsCloudFill,
    BsRocketFill,
    BsBriefcaseFill,
    BsChatDotsFill,
    BsBellFill,
    BsCalendarFill,
    BsClockFill,
    BsFileEarmarkFill,
    BsFolderFill,
    BsCartFill,
    BsCreditCardFill,
    BsTrophyFill,
    BsGiftFill,
    BsBookFill,
    BsCameraFill,
    BsMusicNoteBeamed,
    BsPlayCircleFill,
};

// Get sorted list of available icon names
export const availableIcons = Object.keys(iconMap).sort();

// Function to get icon component from string name
export function getIconComponent(iconName: string): IconType | null {
    return iconMap[iconName] || null;
}

// Function to check if an icon name is valid
export function isValidIcon(iconName: string): boolean {
    return iconName in iconMap;
}
